# Setup
name:         R_B_prince
tagline:      Senior Research Scientist @tencent.com
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


baidu-analysis: 8b87bfecd0084b4c3b52ff5238cfa3ab